// <auto-generated />
namespace InventoryMasterNew.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newmodule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newmodule));
        
        string IMigrationMetadata.Id
        {
            get { return "202206031901020_newmodule"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
